### ISSUE TITLE
Licence file

### ISSUE THREAD

**Issue by Kevincavender** [ReliaQualAssociates/ramstk#1]
I would like to use this project but copyright laws prevent certain use without a license included in the software. I would recommend BSD-3, however, the decision is up to you.

**Comment by weibullguy** [comment]
How are you intending to use the project?

**Comment by Kevincavender** [comment]
To use it for my work

**Comment by weibullguy** [comment]
Added license file to project and license header to source files.  No further action required.  This issue is closed.
