### ISSUE TITLE
gi\gimodule.c: fatal error C1083: Cannot open include file: 'msvc_recommended_pragmas.h': No such file or directory

### ISSUE THREAD

**Issue by AInowG** [ReliaQualAssociates/ramstk#1303]
**Describe the chore that needs to be addressed.**

- [ ] This issue subsumes the following issues:
when i Run poetry install --no-root  ,message below:

gimodule.c
  gi\gimodule.c: fatal error C1083: Cannot open include file: 'msvc_recommended_pragmas.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2

I am Win10 msys2 installed, and 'msvc_recommended_pragmas.h' in system. but error again.

**Comment by weibullguy** [comment]
That's a problem with your PyGobject installation.  Poetry can't install PyGobject on Windows, here are the instructions for installing PyGobject on Windows --> https://pygobject.readthedocs.io/en/latest/getting_started.html#windows-getting-started.
