### ISSUE TITLE
pip or python setup fails with python 3.7.3

### ISSUE THREAD

**Issue by JmiXIII** [ReliaQualAssociates/ramstk#225]
### Expected Behavior ###

As a user, I want to install ramstk and test it.

### pip install or python setup.py install ###

* RAMSTK Version: pypy or github (same behavior)
* Operating System: windows
* OS Distribution (if Linux):
* OS Version: W8.1
* Hardware:
* Required Software Versions:
  * Python == 3.7.3 (Anaconda)

Faill to install eith er via pip or python setup.py install > same issue
"  File "setup.py", line 14, in <module>
    __long_description__ = f.read()
  File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5586: character maps to <undefined>"

Am I alone to have this defect ?

**Comment by weibullguy** [comment]
Probably not.  The problem is the setup.py file doesn't indicate the README.md file's encoding ("utf-8").  I can fix that, but I'll have find a Windows machine to test this on (pull requests are welcome, of course ;)).  However, a little further along in the setup.py file, you'll see this:

if not sys.version_info[0] == 2:
    sys.exit("Sorry, Python 3 is not supported yet.")

So that'll be the ultimate problem trying to use RAMSTK on your system.  The current push is to provide support for Python 3.

**Comment by weibullguy** [comment]
The following modules have been refactored to date:
  * Revision
  * Function
  * Requirement
  * Validation
The develop branch installs and runs using Python 3.7.2 and the Makefile target 'install'.  Recommend installing in a virtual environment or --user if there's an interest in testing what's available to date.

**Comment by weibullguy** [comment]
The following all work on my machine with Python 3.7.4:

`make <PREFIX=/path/to/root_dir> install` and is the preferred method of installation.
`make dist && pip install dist/*.whl`
`python setup.py install`

The attached file is a postgres database dump of a small project that can be used to test RAMSTK.

[ramstk_test_db.sql.txt](https://github.com/ReliaQualAssociates/ramstk/files/5205667/ramstk_test_db.sql.txt)

**Comment by weibullguy** [comment]
`pip install ramstk==0.12.1` will install the latest RAMSTK that works (at least on my machine) with Python 3.6, 3.7, and 3.8.  There are yanked versions that may attempt to install if you `pip install ramstk`, so ensure you pass the version number.
