### ISSUE TITLE
Error When Trying to Build Wheel for Numpy with release v-1.0.0

### ISSUE THREAD

**Issue by Jonathan06891** [ReliaQualAssociates/ramstk#372]
Hello, when trying to run the pip install -r requirements.txt with release v-1.0.0, I run into an error when trying to build the wheel for numpy. Some of the dependencies which pip is claiming it cannot find (such as mkl_rt), I already installed manually in order to keep the installation from returning an error when installing scipy. I'm using Ubuntu 20.04. The full error is below.

[numpy_build_error.txt](https://github.com/ReliaQualAssociates/ramstk/files/5392414/numpy_build_error.txt)

**Comment by weibullguy** [comment]
mkl_rt is just one of many BLAS/LAPACK libraries.  From the attached output, you can see that numpy finds your OpenBLAS and ATLAS installations and is using those libraries to build against.  These are the recommended BLAS/LAPACK implementations for numpy, I think.

That said, you could try `sudo apt install numpy` to get numpy (or any of the dependencies) installed on your system.

**Comment by weibullguy** [comment]
This is an error caused by the OP's machine not having BLAS/LAPACK libraries properly installed, not a RAMSTK issue.
