### ISSUE TITLE
Consider setting 'develop' branch as git default

### ISSUE THREAD

**Issue by rakhimov** [ReliaQualAssociates/ramstk#53]
Awesome project!!!

I suspect the main development is happening in the ``develop`` branch,
and the ``master`` branch is for stable releases.

It would be helpful for contributors to see ``develop`` as default on GitHub.
For example, by default, new contributions/pull-requests will be opened against the ``master`` branch
instead of the current ``develop`` branch.

**Comment by rakhimov** [comment]
> For example, by default, new contributions/pull-requests will be opened against the master branch
> instead of the current develop branch.

I meant this is a current issue with ``master`` being default.

**Comment by weibullguy** [comment]
Good feedback.  Default branch changed to develop.  Thanks for the input.
