### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by rakhimov** [ReliaQualAssociates/ramstk#55]
It would be helpful to provide an easy installation to users with ``pip``.
``setup.py`` already looks configured.
Unfortunately, ``rtk`` name seems to be already taken on [pypi](https://pypi.python.org/pypi?%3Aaction=search&term=rtk&submit=search),
so you need to reserve a new one (e.g., ``rams-tk`` is available).

**Comment by weibullguy** [comment]
This will require renaming RTK to RAMSTK, RAMStk, RAMS.TK, RAMS.tk or similar since RTk is an existing PyPI package.  Additionally, "The Reliability ToolKit" and RTK are potential copyright and trademark infringements; they are both used by several other organizations.

**Comment by weibullguy** [comment]
RAMSTK added to PyPI with upload of v1.0.0dev0 made available on July 18, 2018.
