### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by rakhimov** [ReliaQualAssociates/ramstk#57]
I am not sure why Python 3 is currently not supported (dependencies?),
but if it is trivial transformations like with [2to3](https://docs.python.org/2/library/2to3.html),
it shouldn't be hard.

I can help with this while exploring the source.

**Comment by rakhimov** [comment]
PyGTK doesn't support python 3 and is deprecated in favor of PyGObject.

**Comment by weibullguy** [comment]
Code base updated to Python3 with pull request #198
