### ISSUE TITLE
PyGTK deprecation

### ISSUE THREAD

**Issue by rakhimov** [ReliaQualAssociates/ramstk#58]
According to [pygtk doc](http://www.pygtk.org/),
the GTK+2 bindings are deprecated (since 2011),
and PyGObject is recomended for new projects with GTK+3 bindings.
There's some porting docs on pygobject: https://pygobject.readthedocs.io/en/latest/porting.html

**Comment by rakhimov** [comment]
Since it is mentioned in a project roadmap,
I would also consider options of using Qt (PyQt5, PySide2) or wxWidgets (wxPython).
However, it is likely to require substantial work to change frameworks.

The nice feature of these alternatives is that they allow GUI development with WYSIWYG forms
(i.e., without writing code).
Also, these C++ based frameworks have OOP built-in from the ground-up
unlike the GTK's C with bolted-in OOP ~~atrocity~~.

**Comment by rakhimov** [comment]
Related to python 3 issue #57

**Comment by rakhimov** [comment]
There's [Glade](http://www.pygtk.org/articles/pygtk-glade-gui/Creating_a_GUI_using_PyGTK_and_Glade.htm) for PyGTK to design GUI forms without coding.

**Comment by weibullguy** [comment]
I don't like Glade.  I prefer the control that comes with coding the widgets myself.  I've found Glade works well for smallish GUI's, but as the GUI's become more "complex," Glade tends to require more effort than just coding the widgets.  This is especially true when you create your own classes based on the toolkit widgets.  Also, there are widgets not available in the Glade such as matplotlib plots.

**Comment by weibullguy** [comment]
PyGTK replaced with pygobject (PyGTK3) in pull request #198
