### ISSUE TITLE
RTK prefix vs. rtk namespace

### ISSUE THREAD

**Issue by rakhimov** [ReliaQualAssociates/ramstk#62]
This is more of a question since I couldn't find info in wiki or website.

Some modules/classes/variables have 'RTK' prefix in their names, and others don't.

Is there a rule?

Or is it transitioning to Python namespaces and consistent use of 'rtk'?

**Comment by weibullguy** [comment]
See updated [RTK Coding and Naming Conventions](https://github.com/weibullguy/rtk/wiki/RTK-Coding-and-Naming-Conventions) and let me know if that addresses your question.

**Comment by rakhimov** [comment]
Yep. Now it is well covered in the wiki.
```
The RTK identifies each as belonging to the RTK project. An RTK module would be named <Module>DataModel (i.e., replace the RTK with the CamelCase name of the module). Thus, the Revision data model, data controller, module view, and work view are defined as:

class RevisionDataModel(RTKDataModel):
class RevisionDataController(RTKDataController):
class RevisionModuleView(RTKModuleView):
class RevisionWorkView(RTKWorkView):

"Custom" widgets used to display/manipulate information are derived from the widget toolkit (currently only pyGTK). The resulting widgets have the same name as the base widget, with RTK prepended to indicate it is customized for use in RTK. For example:

* RTKEntry
* RTKLabel
* RTKTreeView

"Customizing" the widgets provides a consistent look and feel to the RTK user interface more so than custom methods/functions. However, some RTK widgets do contain custom methods.
```

However, I wonder if supporting multiple frameworks (PyGTK, PyQt, wxWidgets, ...) is worth the effort.
Why is it important?
I can't recall a project that works across frameworks with the same front-end codebase.
For example, PyQt is very different with signals/slots and Model-View-Delegate
as compared to PyGTK callbacks and MVC.

**Comment by weibullguy** [comment]
It's probably not important.  I know I've used applications with more than one (usually GTK and Qt) GUI toolkit option, but I can't recall them and there aren't many (or any, because I might be remembering things that didn't really happen ;)).  Probably it makes more sense to either move to Python 3/PyGobject or Python 3/Qt in future releases.
